trigger:
- main  # This will trigger the pipeline on commits to the main branch

pool:
  vmImage: 'windows-latest'  # Use a Windows agent

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'  # Specify the Node.js version you need
  displayName: 'Install Node.js'

- task: Npm@1
  displayName: 'Install npm dependencies'
  inputs:
    command: 'install'
    workingDir: '.'  # Assuming your package.json is in the root directory

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
  displayName: 'Archive files'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    ArtifactName: 'backend'
    publishLocation: 'Container'
  displayName: 'Publish Artifact'
- task: AzureRmWebAppDeployment@5
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure for Students (3726fb87-ee7b-42c4-a39c-d437513f686c)'
    appType: 'webApp'
    WebAppName: 'testingportfolio'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
