trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- task: Npm@1
  displayName: 'Install npm dependencies'
  inputs:
    command: 'install'
    workingDir: 'server'  # Ensure this is the correct directory where your package.json is located

- task: Npm@1
  displayName: 'Build the project'
  inputs:
    command: 'custom'
    customCommand: 'run build'
    workingDir: 'server'  # Update if your build script is located elsewhere

- task: CopyFiles@2
  inputs:
    Contents: 'server/**'  # Adjust this path if your build output is in a different directory
    TargetFolder: $(Build.ArtifactStagingDirectory)

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    ArtifactName: 'release'
    publishLocation: 'Container'

- task: AzureRmWebAppDeployment@5
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure for Students (3726fb87-ee7b-42c4-a39c-d437513f686c)'
    appType: 'webApp'
    WebAppName: 'testingportfolio'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
